---
- name: Ensure Java is installed.
  package: "name={{ item }} state=installed"
  with_items: "{{ java_packages }}"
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home